---
version: '2'
services:
  discovery-server:
    image: springcommunity/films-discovery-server
    container_name: discovery-server
    mem_limit: 512M
    entrypoint: ["./dockerize","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
      - 8761:8761
  mongodb_container:
    image: mongo:latest
    environment:
      MONGDB_DATABASE:  films
    #      MONGODB_USER: root
    #      MONGODB_PASSWORD: password
    #      MONGODB_ADMIN_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  films-websocket:
    image: springcommunity/films-websocket-service
    container_name: films-websocket-service
    mem_limit: 512M
    entrypoint: ["./dockerize","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
      - 8080:8080
  films-service:
    image: springcommunity/films-service
    container_name: films-service
    mem_limit: 512M
    depends_on:
      - mongodb_container
      - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://mongodb_container:27017","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
      - 8081:8080
  mongo_seed:
    build: ./mongo-seed
    links:
      - mongodb_container
volumes:
  mongodb_data_container: