version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGDB_DATABASE:  films
#      MONGODB_USER: root
#      MONGODB_PASSWORD: password
#      MONGODB_ADMIN_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:


